name: emania
description: Turning inspiration to application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.1.0+2

dependencies:
  #cached_network_image: "^0.4.1+1"
  flutter:
    sdk: flutter
  dio: ^2.0.14
  splashscreen: ^1.2.0
  font_awesome_flutter: ^8.4.0
  http: ^0.12.0
  flutter_spinkit: ^3.1.0
  #shared_preferences: ^0.5.1+1
  connectivity: ^0.4.2
  show_dialog : ^1.0.3
  #bloc: ^0.9.3
  #rxdart: ^0.21.0
  #square_in_app_payments: ^1.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - media/emania40.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family:  Icons
      fonts:
      - asset: fonts/Icons.ttf
    - family: Quicksand
      fonts:
      - asset: fonts/Quicksand.ttf
      - asset: fonts/Quicksand-Medium.ttf
        weight: 100
